### ISSUE TITLE
Lilypond export

### ISSUE THREAD

**Issue by priyadarshan** [songscribe/SongScribe#1]
Thank you for working on the Lilypond export!

Let me know when you have a stable version to try.

If it is all right, I would like to announce this new feature on reddit (http://www.reddit.com/r/lilypond/), since there are not many editors, as good as `SongScribe`, that manage Lilyond well.

Thank you!

**Comment by kavai77** [comment]
Hi Priyadarshan,
Unfortunately, it is not working yet, because there are some unclear specification points.
I think the specification of Lilypond could be much clearer, e.g. working on ABC was much easier.
Now I try to connect with Ashirvad, because he is also reading the spec, so we could discuss the open issues.

**Comment by priyadarshan** [comment]
I met with Ashirvad in Mondsee (we missed you!), and we spoke at length about some key points. I shall be in touch with him, so that he can submit the work he did.

Meanwhile, thank you so much for the excellent `SongScribe`! Thank you also for hosting it here on GitHub, so that it may be useful to other music lovers as well.

**Comment by ashirvadz** [comment]
Hi Himadri and Priydarshan,
It's great to work with both of you!

**Comment by kavai77** [comment]
Hi Guys,
I am struggling with the main structure of Lilypond. One issue is how to create a multiline song:
**Solution 1 (funny output)**

```
\score {
 \version "2.18.2"
 {
   \new Staff \relative c' {
      \clef treble \key c \major
      \autoBeamOff
      e8 e16 e32 f'8 f16 f32
   }
   \new Staff \relative c' {
      \clef treble \key c \major
      \autoBeamOff
      e8 e16 e32 f'8 f16 f32
    }
  }
}
```

**Solution 2: (the lines are connected with - not good)**

```
\score {
 \version "2.18.2"
 <<
   \new Staff \relative c' {
      \clef treble \key c \major
      \autoBeamOff
      e8 e16 e32 f'8 f16 f32
   }
   \new Staff \relative c' {
      \clef treble \key c \major
      \autoBeamOff
      e8 e16 e32 f'8 f16 f32
    }
  >>
}
```

Any idea how to do this? It also would be nice if I don't have to specify `\autoBeamOff` in each line.

**Comment by ashirvadz** [comment]
Hi Himadri,

The line breaking in Lilypond is a bit tricky, but as with other aspects of it, you can tweak it in many different ways.
Take a look at this, I don't know if it's what you were thinking of:

```
\score {
 \version "2.18.2"
 {
   \new Staff \relative c' {
      \clef treble \key c \major
     \autoBeamOff
      e8 e16 e32 f'8 f16 f32 \bar "" \break
            e8 e16 e32 f'8 f16 f32
    }
  }
}
```

There's some documentation on line breaking [here.](http://www.lilypond.org/doc/v2.16/Documentation/notation/line-breaking)

**Comment by kavai77** [comment]
Hi Ashirvad,
The \break is not the optimal solution, indeed. If these are the only solutions, I think we should reconsider using Lilypond for Sri Chinmoy's songs. The other solution would be to ignore the lines from SongScribe at convert the song as a big Lilypond sequence, and let Lilypond decide where to break the lines. But since we don't use bar lines, this would be anywhere.
So failure to adjust this would be a deal-breaker for Lilypond, I think.
